apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  namespace: webapp-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: webapp
        image: 740165692460.dkr.ecr.us-east-1.amazonaws.com/application:latest
        env:
        - name: DBHOST
          value: mysql-service.mysql-namespace.svc.cluster.local
        - name: DBPORT
          value: "3306"
        - name: BACKGROUND_COLOR
          value: blue
        - name: MYSQL_ROOT_PASSWORD
          value: mypassword
        - name: DBUSER
          value: "root"
        - name: DBPASSWORD
          value: "mypassword" # MySQL password
        ports:
        - containerPort: 8080
