apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: webapp
        image: 740165692460.dkr.ecr.us-east-1.amazonaws.com/application:0.23
        env:
        - name: DBHOST          # to MySQL service name
          value: mysql-service.mysql-namespace.svc.cluster.local
        - name: DBUSER
          value: root
        - name: DBPWD
          value: mypassword
        - name: DATABASE
          value: employees
        - name: DBPORT
          value: "3306"
        ports:
        - containerPort: 8080