apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql-namespace
  labels:
    app: mysql
spec:
  imagePullSecrets:
    - name: ecr-secret
  containers:
  - name: mysql
    image: 740165692460.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: mypassword
    ports:
    - containerPort: 3306