apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webapp-namespace
  labels:
    app: employees
spec:
  containers:
  - name: webapp
    image: 740165692460.dkr.ecr.us-east-1.amazonaws.com/application:latest
    env:
    - name: BACKGROUND_COLOR
      value: blue
    ports:
    - containerPort: 8080