apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webapp-namespace
  labels:
    app: employees
spec:
  imagePullSecrets:
    - name: ecr-secret
  containers:
  - name: webapp
    image: 740165692460.dkr.ecr.us-east-1.amazonaws.com/application:0.23
    env:
    - name: BACKGROUND_COLOR
      value: blue
    - name: DBHOST
      value: mysql-service.mysql-namespace.svc.cluster.local  # MySQL Service DNS Name
    - name: DBUSER
      value: root                  # MySQL Username
    - name: DBPWD
      value: mypassword           # MySQL Password
    - name: DATABASE
      value: employees             # Database Name
    - name: DBPORT
      value: "3306"
    ports:
    - containerPort: 8080
