apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp-namespace
spec:
  type: LoadBalancer  #NodePort
  selector:
    app: employees
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  #externalTrafficPolicy: Cluster
